on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
      - name: Build pdf
        uses: docker://pandoc/ubuntu-latex
        with:
          entrypoint: build-pdf.sh
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
