on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew install pandoc
          brew install pandoc-crossref
          sudo apt-get install texlive-full
          mkdir output  # create output dir
          # this will also include README.md
          #echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
      - run: |
          pandoc \
            --pdf-engine=xelatex \
            --template=./templates/eisvogel.latex \
            --highlight-style tango \
            --toc -N \
            --filter pandoc-crossref \
            --output build/book.pdf \
            src/metadata.txt src/*.md
      - run: |
          pandoc \
            --filter pandoc-crossref \
            --css templates/epub.css \
            --toc -N \
            --output build/book.epub \
            src/metadata.txt src/*.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
