on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew install pandoc
          brew install pandoc-crossref
          sudo apt-get install texlive-xetex
          mkdir build
      - run: |
          pandoc \
            --pdf-engine=xelatex \
            --template=./templates/eisvogel.tex \
            --highlight-style tango \
            --toc \
            --number-sections \
            --filter pandoc-crossref \
            --output build/book.pdf \
            src/metadata.txt src/*.md
      - run: |
          pandoc \
            --filter pandoc-crossref \
            --css templates/epub.css \
            --toc \
            --number-sections \
            --output build/book.epub \
            src/metadata.txt src/*.md
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
